# Generated by Django 5.0.1 on 2024-01-10 00:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="callbackinformation",
            name="date_created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
