# Generated by Django 5.0.6 on 2024-06-30 10:40

import shared.fields.uild
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_callbackinformation_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callbackinformation',
            name='id',
            field=shared.fields.uild.ULIDField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
